# Generated by Django 5.0 on 2025-12-18 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='admin_dashb_user_id_cb4b17_idx',
            old_name='admin_dashb_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='admin_dashb_action_8c49e4_idx',
            old_name='admin_dashb_action_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='admin_dashb_timesta_d85a46_idx',
            old_name='admin_dashb_timestamp_idx',
        ),
    ]
