# Generated by Django 5.0 on 2025-12-08 04:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Amenities',
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('property_type', models.CharField(choices=[('lodge', 'Lodge'), ('cottage', 'Cottage'), ('room', 'Room'), ('apartment', 'Apartment'), ('house', 'House'), ('villa', 'Villa')], max_length=20)),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='Latitude and Longitude', srid=4326)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('suburb', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField()),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending_approval', 'Pending Approval')], default='pending_approval', max_length=20)),
                ('main_image', models.ImageField(upload_to='properties/%Y/%m/%d/')),
                ('max_guests', models.IntegerField(default=2)),
                ('bedrooms', models.IntegerField(default=1)),
                ('bathrooms', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenities', models.ManyToManyField(blank=True, to='properties.amenity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
