# Generated by Django 5.0 on 2025-12-10 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_initial'),
        ('properties', '0002_savedproperty'),
    ]

    operations = [
    ]
