# Generated by Django 5.0 on 2025-12-18 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_merge_0002_initial_0002_savedproperty'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='savedproperty',
            new_name='properties__user_id_667586_idx',
            old_name='properties_s_user_id_5a3b4c_idx',
        ),
        migrations.RenameIndex(
            model_name='savedproperty',
            new_name='properties__user_id_c63d13_idx',
            old_name='properties_s_user_id_9d6e2f_idx',
        ),
    ]
