# Generated by Django 5.0 on 2025-12-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_rename_properties_s_user_id_5a3b4c_idx_properties__user_id_667586_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='properties/%Y/%m/%d/'),
        ),
    ]
